create table if not exists
  public.invoices (
    id bigint generated by default as identity,
    created_at timestamp with time zone not null default now(),
    invoice_number text null,
    invoice_amount real null,
    due_date date not null,
    user_id uuid not null,
    notifications_on boolean not null default false,
    supplier_name text null,
    constraint invoices_pkey primary key (id),
    constraint invoices_user_id_fkey foreign key (user_id) references auth.users (id) on update cascade on delete cascade
  ) tablespace pg_default;